project:
  type: website
  output-dir: docs

website:
  title: "BIO376"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Unit 1"
        contents:
          - L1.qmd
          - Methods.qmd
          - L2.qmd
          - L3.qmd
      - section: "Unit 2"
        contents: 
          - L4.qmd
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

